//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_ice_attack2009.html
halflife.wad
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
cstrike.wad
cs_office.wad
chateau.wad
de_storm.wad
maps/zm_ice_attack2009.bsp
